# Generated by Django 4.2.7 on 2024-01-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField(default='default')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
